# Generated by Django 5.0.7 on 2024-08-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlogin', '0007_patient_user_alter_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
