# Generated by Django 5.0.7 on 2024-08-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlogin', '0010_appointmentdata_delete_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdata',
            name='ap_endTime',
            field=models.DateTimeField(),
        ),
    ]
