# Generated by Django 5.0.7 on 2024-08-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formlogin', '0004_draft_imagepost_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='category',
            new_name='dCategory',
        ),
        migrations.RenameField(
            model_name='draft',
            old_name='content',
            new_name='dContent',
        ),
        migrations.RenameField(
            model_name='draft',
            old_name='image',
            new_name='dImage',
        ),
        migrations.RenameField(
            model_name='draft',
            old_name='summary',
            new_name='dSummary',
        ),
        migrations.RenameField(
            model_name='draft',
            old_name='title',
            new_name='dTitle',
        ),
        migrations.RenameField(
            model_name='imagepost',
            old_name='category',
            new_name='iCategory',
        ),
        migrations.RenameField(
            model_name='imagepost',
            old_name='content',
            new_name='iContent',
        ),
        migrations.RenameField(
            model_name='imagepost',
            old_name='image',
            new_name='iImage',
        ),
        migrations.RenameField(
            model_name='imagepost',
            old_name='summary',
            new_name='iSummary',
        ),
        migrations.RenameField(
            model_name='imagepost',
            old_name='title',
            new_name='iTitle',
        ),
    ]
